### ISSUE TITLE
Linux Release VST3 binary file missing

### ISSUE THREAD

**Issue by crshrprt** [yeeking/ai-improviser-plugin#1]
Thank you for this interesting plugin. 
I noticed that in the Linux release zip file only the standalone application is found while the VST3 plugin binary is missing:
```
ai-improviser-plugin-linux-v0.1/
├── ai-midi-improviser
└── ai-midi-improviser.vst3
    └── Contents
        └── x86_64-linux
```

**Comment by yeeking** [comment]
Thanks for reporting this. I have updated the linux zip. Should be like this now: 

No idea if it'll work on anyone else's linux but the cmake build should work if not.  

```
ai-improviser-plugin-linux-v0.1
|-- ai-midi-improviser
`-- ai-midi-improviser.vst3
    `-- Contents
        `-- x86_64-linux
            `-- ai-midi-improviser.so

```

**Comment by crshrprt** [comment]
Thanks. It works fine now.
